In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("population-and-growth-rates-by-districts-of-census-1951-2017-in-punjab-pakistan.csv")

In [4]:
df.head()

,Province/division/ district,Population ( in '1000' ) in 1951,Population ( in '1000' ) in 1961,Population ( in '1000' ) in 1972,Population ( in '1000' ) in 1981,Population ( in '1000' ) in 1998,Population ( in '1000' ) in 2017,Average annual growth rate (%) in 1961,Average annual growth rate (%) in 1972,Average annual growth rate (%) in 1981,Average annual growth rate (%) in 1998,Average annual growth rate (%) in 2017
0,PUNJAB,"20,541","25,464","37,607","47,292","73,621","109,990",2.19,3.41,2.75,2.64,2.13
1,Bahawalpur Division,"1,823","2,574","3,544","4,669","7,636","11,453",3.54,2.79,3.32,2.93,2.15
2,Bahawalnagar,630,823,"1,074","1,374","2,061","2,976",2.72,2.32,2.96,2.41,1.95
3,Bahawalpur,528,736,"1,071","1,453","2,433","3,669",3.40,3.29,3.68,3.08,2.18
4,Rahim Yar Khan,664,"1,016","1,399","1,841","3,141","4,808",4.37,2.79,3.31,3.19,2.26

In [5]:
df.shape

(46, 12)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 12 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Province/division/ district              46 non-null     str
 1   Population ( in '1000' ) in 1951         46 non-null     str
 2   Population ( in '1000' ) in 1961         46 non-null     str
 3   Population ( in '1000' ) in 1972         46 non-null     str
 4   Population ( in '1000' ) in 1981         46 non-null     str
 5   Population ( in '1000' ) in 1998         46 non-null     str
 6   Population ( in '1000' ) in 2017         46 non-null     str
 7   Average annual growth rate (%) in 1961   46 non-null     float64
 8   Average annual growth rate (%) in  1972  46 non-null     float64
 9   Average annual growth rate (%) in  1981  46 non-null     float64
 10  Average annual growth rate (%) in  1998  46 non-null     float64
 11  Average annual growth rate (%) in  2017  46 non-null     float64
dtypes: float64(5), str(7)
memory usage: 4.4 KB

In [7]:
df.describe()

,Average annual growth rate (%) in 1961,Average annual growth rate (%) in 1972,Average annual growth rate (%) in 1981,Average annual growth rate (%) in 1998,Average annual growth rate (%) in 2017
count,46.000000,46.000000,46.000000,46.000000,46.000000
mean,2.191957,3.374348,2.776087,2.544783,2.045652
std,0.947658,0.557728,0.875809,0.556037,0.416347
min,0.720000,2.080000,0.610000,0.630000,1.370000
25%,1.507500,2.985000,2.140000,2.222500,1.740000
50%,2.190000,3.380000,2.975000,2.455000,1.975000
75%,2.552500,3.722500,3.392500,2.825000,2.210000
max,5.400000,5.260000,4.210000,3.980000,3.160000

@channel

# Wednesday — Pandas Fundamentals I

**Goal:** Loading, inspecting, filtering, and selecting data confidently.

## Implementation Task

Load a real public dataset (e.g. Titanic or a Pakistani economic dataset from Kaggle), answer 8 specific business questions about it purely using Pandas filtering/selection (no visualization yet).

**Deliverable:** Jupyter/Colab notebook with the 8 answers + code.

Solve short hands-on challenges to perfect your data manipulation skills.

In [9]:
df.columns

Index(['Province/division/ district', 'Population ( in '1000' ) in 1951',
       'Population ( in '1000' ) in 1961', 'Population ( in '1000' ) in 1972',
       'Population ( in '1000' ) in 1981', 'Population ( in '1000' ) in 1998',
       'Population ( in '1000' ) in 2017',
       'Average annual growth rate (%) in 1961',
       'Average annual growth rate (%) in  1972',
       'Average annual growth rate (%) in  1981',
       'Average annual growth rate (%) in  1998',
       'Average annual growth rate (%) in  2017'],
      dtype='str')

In [10]:
df.columns = [
    "region",
    "population_1951",
    "population_1961",
    "population_1972",
    "population_1981",
    "population_1998",
    "population_2017",
    "growth_1961",
    "growth_1972",
    "growth_1981",
    "growth_1998",
    "growth_2017"
]

In [11]:
df.head(5)

,region,population_1951,population_1961,population_1972,population_1981,population_1998,population_2017,growth_1961,growth_1972,growth_1981,growth_1998,growth_2017
0,PUNJAB,"20,541","25,464","37,607","47,292","73,621","109,990",2.19,3.41,2.75,2.64,2.13
1,Bahawalpur Division,"1,823","2,574","3,544","4,669","7,636","11,453",3.54,2.79,3.32,2.93,2.15
2,Bahawalnagar,630,823,"1,074","1,374","2,061","2,976",2.72,2.32,2.96,2.41,1.95
3,Bahawalpur,528,736,"1,071","1,453","2,433","3,669",3.40,3.29,3.68,3.08,2.18
4,Rahim Yar Khan,664,"1,016","1,399","1,841","3,141","4,808",4.37,2.79,3.31,3.19,2.26

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           46 non-null     str
 1   population_1951  46 non-null     str
 2   population_1961  46 non-null     str
 3   population_1972  46 non-null     str
 4   population_1981  46 non-null     str
 5   population_1998  46 non-null     str
 6   population_2017  46 non-null     str
 7   growth_1961      46 non-null     float64
 8   growth_1972      46 non-null     float64
 9   growth_1981      46 non-null     float64
 10  growth_1998      46 non-null     float64
 11  growth_2017      46 non-null     float64
dtypes: float64(5), str(7)
memory usage: 4.4 KB

In [14]:
population_cols = [
    "population_1951",
    "population_1961",
    "population_1972",
    "population_1981",
    "population_1998",
    "population_2017"
]

In [15]:
for col in population_cols:
 df[col] = df[col].str.replace(",", "").astype(int)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           46 non-null     str
 1   population_1951  46 non-null     int64
 2   population_1961  46 non-null     int64
 3   population_1972  46 non-null     int64
 4   population_1981  46 non-null     int64
 5   population_1998  46 non-null     int64
 6   population_2017  46 non-null     int64
 7   growth_1961      46 non-null     float64
 8   growth_1972      46 non-null     float64
 9   growth_1981      46 non-null     float64
 10  growth_1998      46 non-null     float64
 11  growth_2017      46 non-null     float64
dtypes: float64(5), int64(6), str(1)
memory usage: 4.4 KB

In [17]:
df.head(5)

,region,population_1951,population_1961,population_1972,population_1981,population_1998,population_2017,growth_1961,growth_1972,growth_1981,growth_1998,growth_2017
0,PUNJAB,20541,25464,37607,47292,73621,109990,2.19,3.41,2.75,2.64,2.13
1,Bahawalpur Division,1823,2574,3544,4669,7636,11453,3.54,2.79,3.32,2.93,2.15
2,Bahawalnagar,630,823,1074,1374,2061,2976,2.72,2.32,2.96,2.41,1.95
3,Bahawalpur,528,736,1071,1453,2433,3669,3.40,3.29,3.68,3.08,2.18
4,Rahim Yar Khan,664,1016,1399,1841,3141,4808,4.37,2.79,3.31,3.19,2.26

In [18]:
df.isnull().sum()

region             0
population_1951    0
population_1961    0
population_1972    0
population_1981    0
population_1998    0
population_2017    0
growth_1961        0
growth_1972        0
growth_1981        0
growth_1998        0
growth_2017        0
dtype: int64

# Business Qsts

## Q1. Which 5 regions had the highest population in 2017?

In [53]:
highest_population_2017 = df.sort_values("population_2017",ascending=False).head(5)
highest_population_2017[["region","population_2017"]]

                 region  population_2017
0                PUNJAB           109990
22      Lahore Division            19390
15  Gujranwala Division            16121
10  Faisalabad Division            14185
31      Multan Division            12268

## Q2. Which 5 regions had the lowest population in 2017?

In [54]:
lowest_population_2017 = df.sort_values("population_2017").head(5)
lowest_population_2017[["region","population_2017"]]

           region  population_2017
18      Hafizabad             1157
39         Jhelum             1222
43        Khushab             1280
25  Nankana sahib             1355
13        Chiniot             1369

## Q3. How many regions had a growth rate above 2.5% in 2017?

In [29]:
greater_than_2pt5 = df["growth_2017"] > 2.5
print(greater_than_2pt5)

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
Name: growth_2017, dtype: bool

In [31]:
print(greater_than_2pt5.sum())

8

## Q4. How many regions had a growth rate below 1.8% in 2017?

In [32]:
below_rate_1pt8= df["growth_2017"]<1.8
print(below_rate_1pt8)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17     True
18     True
19     True
20     True
21    False
22    False
23    False
24    False
25     True
26    False
27     True
28     True
29    False
30     True
31    False
32    False
33    False
34    False
35     True
36    False
37    False
38     True
39     True
40    False
41    False
42    False
43    False
44    False
45     True
Name: growth_2017, dtype: bool

In [34]:
print(below_rate_1pt8.sum())

13

## Q5. What was the average growth rate in 2017 across all regions?

In [44]:
avg_growth_rate_2017 = df["growth_2017"].mean()
avg_growth_rate_2017 = round(avg_growth_rate_2017,2)
print(avg_growth_rate_2017)

2.05

## Q6. Which region had the highest growth rate in 2017?

In [55]:
highest_growth_rate_2017 = df.sort_values("growth_2017",ascending=False).head(1)
highest_growth_rate_2017[["region","growth_2017"]]

     region  growth_2017
9  Rajanpur         3.16

## Q7. Show all regions whose 2017 population exceeded 5,000.

In [48]:
df[df["population_2017"] > 5000][["region","population_2017"]]

                 region  population_2017
0                PUNJAB           109990
1   Bahawalpur Division            11453
5     D.G.Khan Division            11021
10  Faisalabad Division            14185
11           Faisalabad             7882
15  Gujranwala Division            16121
16           Gujranwala             5011
22      Lahore Division            19390
24               Lahore            11120
27     Sahiwal Division             7378
31      Multan Division            12268
36  Rawalpindi Division            10007
40           Rawalpindi             5402
41    Sargodha Division             8167

## Q8. Which regions experienced population growth of more than 3× from 1951 to 2017?

In [49]:
df[df["population_2017"] > df["population_1951"] * 3]["region"]

0                  PUNJAB
1     Bahawalpur Division
2            Bahawalnagar
3              Bahawalpur
4          Rahim Yar Khan
5       D.G.Khan Division
6                D.G.Khan
7                  Layyah
8            Muzaffargarh
9                Rajanpur
10    Faisalabad Division
11             Faisalabad
12                  Jhang
13                Chiniot
14              T.T.Singh
15    Gujranwala Division
16             Gujranwala
17                 Gujrat
18              Hafizabad
19      Mandi Baha-ud-Din
20                Narowal
21                Sialkot
22        Lahore Division
23                  Kasur
24                 Lahore
25          Nankana sahib
26            Sheikhupura
27       Sahiwal Division
28                  Okara
29              Pakpattan
30                Sahiwal
31        Multan Division
32               Khanewal
33                Lodhran
34                 Multan
35                 Vehari
36    Rawalpindi Division
37                 Attock
38                Chakwal
39                 Jhelum
40             Rawalpindi
41      Sargodha Division
42                Bhakkar
43                Khushab
44               Mianwali
45               Sargodha
Name: region, dtype: str